version: "3.9"
services:
  rent_database:
    image: mysql/mysql-server:5.6
    container_name: spring-rent-api-solutions
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "rent"

  velib_stations_database:
    image: mysql/mysql-server:5.6
    container_name: spring-velib-stations-api-solutions
    expose:
      - "3306"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "velib_stations"